Models/EntityConfiguration/EntitySystem/Entitys/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.Entitys
{
    public class Message
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }

        [ForeignKey("ThemeId")]
        public int ThemeId { get; set; }

        public Theme Theme { get; set; }

        public AddresSent AddresSent { get; set; }

        public MessageSettings MessageSettings { get; set; }

        public string MessageText { get; set; }

        public string DateCreate { get; set; }

        public bool IsRead { get; set; }

        public bool IsHidden { get; set; }
    }
}

Controllers/FrontController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using OpenSourceEntitys.Models;
using OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.Entitys;
using OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.SystemStorage.StorageEntityContext.UnitOfWork;
using OpenSourceEntitys.Models.ModelControllers;

namespace OpenSourceEntitys.Controllers
{
    public class FrontController : Controller
    {
        private readonly ILogger<FrontController> _logger;

        private IUnitOfWork UnitOfWork { get; set; }

        private UserManager<User> UserManager { get; set; }

        public FrontController(
            ILogger<FrontController> logger,
            IUnitOfWork UnitOfWork,
            UserManager<User> UserManager
            )
        {
            _logger = logger;
            this.UnitOfWork = UnitOfWork;
            this.UserManager = UserManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(new Front
            {
                GroupCount = UnitOfWork.RepositoryGroups.GetEntitys().Result.Count(),
                ParticipantCount = UnitOfWork.RepositoryParticipant.GetEntitys().Result.Count()
            }) ;
        }

        [HttpPost]
        public async Task<IActionResult> Index(Front front)
        {
            if (ModelState.IsValid)
            {
                var searchreguesr = await UserManager.FindByEmailAsync(front.Email);

                if(searchreguesr == null)
                {
                    return RedirectToActionPermanent("Index","Registration", new { FrontEmail = front.Email });
                }
            }

            return View(new Front
            {
                GroupCount = UnitOfWork.RepositoryGroups.GetEntitys().Result.Count(),
                ParticipantCount = UnitOfWork.RepositoryParticipant.GetEntitys().Result.Count()
            });
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ListUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.ApplicationContext;
using OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.Entitys;
using OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.SystemStorage.StorageEntityContext.RepositoryLogger.IUnitLogOfWork;
using OpenSourceEntitys.Models.ModelControllers;
using OpenSourceEntitys.Models.ModelControllers.ListUsers.ListUserService;
using OpenSourceEntitys.Models.ModelControllers.ListUsersView;
using OpenSourceEntitys.Models.ModelCore;
using static OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.SystemStorage.StorageEntityContext.RepositoryLogger.LoggingTypes.LoggingEnum;
using static OpenSourceEntitys.Models.ModelControllers.ListUsers.ListUserService.ListParticipantSorting;

namespace OpenSourceEntitys.Controllers
{
    [Authorize]
    public class ListUserController : Controller
    {
        private readonly ILogger<ListUserController> _logger;

        private UserManager<User> UserManager { get; set; }

        private IListParticipantService IListUserService { get; set; }

        private EntitySourceContext EntitySourceContext { get; set; }

        private IUnitLogOfWork UnitLogOfWork { get; set; }

        public ListUserController(
            ILogger<ListUserController> logger,
            IListParticipantService IListUserService,
            UserManager<User> UserManager,
            EntitySourceContext EntitySourceContext,
            IUnitLogOfWork UnitLogOfWork
            )
        {
            _logger = logger;
            this.UserManager = UserManager;
            this.EntitySourceContext = EntitySourceContext;
            this.IListUserService = IListUserService;
            this.UnitLogOfWork = UnitLogOfWork;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string UserId, string MiddleName, string Name, string LastName, string Email, string UserName, int page = 1, Sorting Sorting = Sorting.NameAsc)
        {
            var listuser = await IListUserService.GetListUserService();

            ListParticipantFiltering ListUsersFiltering = new ListParticipantFiltering(listuser);

            var filtering = ListUsersFiltering.ListUsersGetFiltering(MiddleName, Name, LastName, Email, UserName);

            ListParticipantSorting ListParticipantSorting = new ListParticipantSorting(Sorting);

            var sorting = ListParticipantSorting.GetListParticipantSorting(filtering, Sorting);

            ListParticipantPagination ListUsersPagination = new ListParticipantPagination(page, 7, listuser.Count());

            await UnitLogOfWork.RepositoryLogging.InsertLog(UserId, InformationLoggingEnum.Gettinguserpagedata);

            return View(new ListUser
            {
                MiddleName = MiddleName,
                Name = Name,
                LastName = LastName,
                UserId = UserId,
                Email = Email,
                UserName = UserName,
                Participants = sorting.Skip((page - 1) * 7).Take(7),
                ListUsersSorting = ListParticipantSorting,
                ListUsersPagination = ListUsersPagination,
                HelpersDisplayCountMessage = EntitySourceContext.addresSents
                .Include(t => t.User).Where(t => t.UserId == UserId || t.RecipientId == UserId).ToList().Count(),
                HelpersDeletedCountMessage = EntitySourceContext.MessageSettings
                .Include(t => t.Message).ThenInclude(t => t.AddresSent).ThenInclude(t => t.User)
                .Where(t => (t.UserId == UserId && t.MessageDonorIsHidden == true)
                || (t.UserRecipientId == UserId && t.MessageRecipientIsHidden == true)).ToList().Count()

            }); 

        }
    }
}

Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.ApplicationContext;
using OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.Entitys;
using OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.SystemStorage.StorageEntityContext.RepositoryLogger.IUnitLogOfWork;
using OpenSourceEntitys.Models.ModelControllers;
using OpenSourceEntitys.Models.ModelControllers.ListUsers.ListUserForMessages;
using OpenSourceEntitys.Models.ModelControllers.ListUsers.ListUserViewMessages;
using OpenSourceEntitys.Models.ServiceMessage;
using static OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.SystemStorage.StorageEntityContext.RepositoryLogger.LoggingTypes.LoggingEnum;
using static OpenSourceEntitys.Models.ModelControllers.ListUsers.ListUserForMessages.ListUserForMessageSorting;
using static OpenSourceEntitys.Models.ModelControllers.ListUsers.ListUserViewMessages.ListUserMessageSorting;

namespace OpenSourceEntitys.Controllers
{
    [Authorize]
    public class MessageController : Controller
    {
        private readonly ILogger<MessageController> _logger;

        private UserManager<User> UserManager { get; set; }

        private EntitySourceContext EntitySourceContext { get; set; }

        private IServiceMessage IServiceMessage { get; set; }

        private IUnitLogOfWork UnitLogOfWork { get; set; }

        public MessageController(
            ILogger<MessageController> logger,
            UserManager<User> UserManager,
            EntitySourceContext EntitySourceContext,
            IServiceMessage IServiceMessage,
            IUnitLogOfWork UnitLogOfWork
            )
        {
            _logger = logger;
            this.UserManager = UserManager;
            this.EntitySourceContext = EntitySourceContext;
            this.IServiceMessage = IServiceMessage;
            this.UnitLogOfWork = UnitLogOfWork;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string UserId, string MiddleName, string Name, string LastName, string Email, int page = 1, MessageSorting Sorting = MessageSorting.NameAsc)
        {
            var listuser = await IServiceMessage.GetListSendUser();

            ListUserMessageFiltering ListUserMessageFiltering = new ListUserMessageFiltering(listuser);

            var filtering = ListUserMessageFiltering.ListUsersGetFiltering(MiddleName, Name, LastName, Email);

            ListUserMessageSorting ListParticipantSorting = new ListUserMessageSorting(Sorting);

            var sorting = ListParticipantSorting.GetListParticipantMessageSorting(filtering, Sorting);

            ListUserMessagePagination ListUsersPagination = new ListUserMessagePagination(page, 7, listuser.Count());

            await UnitLogOfWork.RepositoryLogging.InsertLog(UserId, InformationLoggingEnum.Sendingamessage);

            return View(new ListMessage
            {
                MiddleName = MiddleName,
                Name = Name,
                LastName = LastName,
                UserId = UserId,
                Participants = sorting.Skip((page - 1) * 7).Take(7),
                ListUserMessageSorting = ListParticipantSorting,
                ListUserMessagePagination = ListUsersPagination,
                HelpersDisplayCountMessage = EntitySourceContext.addresSents
                .Include(t => t.User).Where(t => t.UserId == UserId || t.RecipientId == UserId).ToList().Count(),
                HelpersDeletedCountMessage = EntitySourceContext.MessageSettings
                .Include(t => t.Message).ThenInclude(t => t.AddresSent).ThenInclude(t => t.User)
                .Where(t => (t.UserId == UserId && t.MessageDonorIsHidden == true)
                || (t.UserRecipientId == UserId && t.MessageRecipientIsHidden == true)).ToList().Count()

            });
        }

        [HttpGet]
        public async Task<IActionResult> MessageSend(string UserSenderId, string UserRecipientId)
        {
            if(!string.IsNullOrEmpty(UserSenderId) && !string.IsNullOrEmpty(UserRecipientId))
            {
                var UserSenders = await UserManager.FindByIdAsync(UserSenderId);

                var UserRecipient = await UserManager.FindByIdAsync(UserRecipientId);

                await UnitLogOfWork.RepositoryLogging.InsertLog(UserSenderId, InformationLoggingEnum.Gettingpagedataforsendingamessage);

                return View(new MessageSend
                {
                    UserId = UserSenderId,
                    UserName = UserSenders.UserName,
                    UserRecipientId = UserRecipientId,
                    UserRecipientName = UserRecipient.UserName,
                    HelpersDisplayCountMessage = EntitySourceContext.addresSents
                    .Include(t => t.User).Where(t => t.UserId == UserSenderId || t.RecipientId == UserSenderId).ToList().Count(),
                    HelpersDeletedCountMessage = EntitySourceContext.MessageSettings
                    .Include(t => t.Message).ThenInclude(t => t.AddresSent).ThenInclude(t => t.User)
                    .Where(t => (t.UserId == UserSenderId && t.MessageDonorIsHidden == true)
                    || (t.UserRecipientId == UserSenderId && t.MessageRecipientIsHidden == true)).ToList().Count()
                });
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> MessageSend(MessageSend MessageSend)
        {
            if(ModelState.IsValid)
            {
               await  IServiceMessage.MessageSent(
                   MessageSend.Theme,
                   MessageSend.Text,
                   MessageSend.UserId,
                   MessageSend.UserRecipientId
                   );
            }

            await UnitLogOfWork.RepositoryLogging.InsertLog(MessageSend.UserId, InformationLoggingEnum.Sendingamessage);

            return View(new MessageSend
            {
                UserId = MessageSend.UserId,
                UserName = MessageSend.UserName,
                UserRecipientId = MessageSend.UserRecipientId,
                UserRecipientName = MessageSend.UserName,
                Theme = MessageSend.Theme,
                Text = MessageSend.Text,
                HelpersDisplayCountMessage = EntitySourceContext.addresSents
                .Include(t => t.User).Where(t => t.UserId == MessageSend.UserId || t.RecipientId == MessageSend.UserId).ToList().Count(),
                HelpersDeletedCountMessage = EntitySourceContext.MessageSettings
                .Include(t => t.Message).ThenInclude(t => t.AddresSent).ThenInclude(t => t.User)
                .Where(t => (t.UserId == MessageSend.UserId && t.MessageDonorIsHidden == true)
                || (t.UserRecipientId == MessageSend.UserId && t.MessageRecipientIsHidden == true)).ToList().Count()
            });
        } 

        [HttpGet]
        public async Task<IActionResult> MessageForUsers(string UserId, string MiddleName, string Name, string LastName, string Email, int? MessageId, int OperationBasket = 0, int page = 1, MessageForSorting Sorting = MessageForSorting.NameAsc)
        {

            if(MessageId != null)
                await IServiceMessage.BasketMessage(OperationBasket, UserId, MessageId);

            var listuser = await IServiceMessage.GetMessageSentsForUsers(UserId);

            ListUserForMessageFiltering ListUserMessageFiltering = new ListUserForMessageFiltering(listuser);

            var filtering = ListUserMessageFiltering.ListUsersGetFiltering(MiddleName, Name, LastName, Email);

            ListUserForMessageSorting ListUserForMessageSorting = new ListUserForMessageSorting(Sorting);

            var sorting = ListUserForMessageSorting.GetListAddresSentMessageForSorting(filtering, Sorting);

            ListUserForMessagePagination ListUserForMessagePagination = new ListUserForMessagePagination(page, 7, listuser.Count());

            await UnitLogOfWork.RepositoryLogging.InsertLog(UserId, InformationLoggingEnum.Sendingamessage);

            return View(new MessageForUsers
            {
                MiddleName = MiddleName,
                Name = Name,
                LastName = LastName,
                UserId = UserId,
                Email = Email,
                AddresSents  = sorting.Skip((page - 1) * 7).Take(7).OrderByDescending(t => t.id),
                ListUserForMessageSorting = ListUserForMessageSorting,
                ListUserForMessagePagination = ListUserForMessagePagination,
                HelpersDisplayCountMessage = EntitySourceContext.addresSents
                .Include(t => t.User).Where(t => t.UserId == UserId || t.RecipientId == UserId).ToList().Count(),
                HelpersDeletedCountMessage = EntitySourceContext.MessageSettings
                .Include(t => t.Message).ThenInclude(t => t.AddresSent).ThenInclude(t => t.User)
                .Where(t => (t.UserId == UserId && t.MessageDonorIsHidden == true)
                || (t.UserRecipientId == UserId && t.MessageRecipientIsHidden == true)).ToList().Count()

            });
        }

        [HttpGet]
        public async Task<IActionResult> MessageRead(string UserId, int MessageId)
        {
            var message = await IServiceMessage.GetReadMessageAsync(UserId,MessageId);

            var donor = await UserManager.FindByIdAsync(message.UserId);

            var recip = await UserManager.FindByIdAsync(message.RecipientId);

            await UnitLogOfWork.RepositoryLogging.InsertLog(UserId, InformationLoggingEnum.Gettingmessageviewformdata);

            return View(new MessageRead
            {
                MessageReadId = MessageId,
                UserId = UserId,
                RecipientId = message.RecipientId,

Views/Message/Index.cshtml
@model OpenSourceEntitys.Models.ModelControllers.ListMessage


@{
    ViewData["Title"] = "Index";
}

<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="~/css/font-awesome-4.7.0\css\font-awesome.min.css">
    <link rel="stylesheet" href="~/css/main.css">
    <link rel="stylesheet" href="~/css/HomeFrontMenu.css">
    <link rel="stylesheet" href="~/css/HomeMenu.css">
    <link rel="stylesheet" href="~/css/Message.css">
    <title></title>
</head>
<body>
    <div class="list-navigation">
        <nav>
            <ul>
                <li><i class="search-f fa fa-search" aria-hidden="true"><input type="text" name="" value=""></i></li>
            </ul>
            <ul class="pos">
                <li><a href="@Url.Action("Index", "Front")"><i class="fa fa-globe" aria-hidden="true"></i>Главная</a></li>
                <li><a href="@Url.Action("ListUsersGroups","Group")"><i class="fa fa-users" aria-hidden="true"></i>Группы</a></li>
                <li><a href="@Url.Action("Index", "Registration")"><i class="fa fa-user-plus" aria-hidden="true"></i>Регистрация</a></li>
                <li><a href="@Url.Action("OutAccount", "Home",new { UserId = @Model.UserId })"><i class="fa fa-user" aria-hidden="true"></i>Выход</a></li>
                <li><a href="@Url.Action("Index", "Front")"><i class="fa fa-map-o" aria-hidden="true"></i>О Сайте</a></li>
            </ul>
        </nav>
    </div>
    <div class="base-container-home">
        <div class="base-home-menu">
            <nav class="">
                <ul>
                    <li><a href="@Url.Action("Index","Home")"><i class="fa fa-user-o" aria-hidden="true"></i>Профиль</a></li>
                    <li><a href="@Url.Action("Index","ListUser",new { UserId = @Model.UserId })"><i class="fa fa-users" aria-hidden="true"></i>Список пользователей</a></li>
                    <li><a href="@Url.Action("UpdateProfile","Home",new { UserId = @Model.UserId })"><i class="fa fa-list-alt" aria-hidden="true"></i>Изменить данные профиля</a></li>
                    <li><a href="@Url.Action("UpdateAccount","Home",new { UserId = @Model.UserId })"><i class="fa fa-list-alt" aria-hidden="true"></i>Изменить данные пользователя</a></li>
                    <li><a href="@Url.Action("UpdatePassword","Home",new { UserId = @Model.UserId })"><i class="fa fa-list-alt" aria-hidden="true"></i>Изменить пароль</a></li>
                    <li><a href="@Url.Action("ListUsersGroups","Group",new { UserId = @Model.UserId })"><i class="fa fa-users" aria-hidden="true"></i>Список групп</a></li>
                    <li><a href="@Url.Action("AppendGroups","Group",new { UserId = @Model.UserId })"><i class="fa fa-users" aria-hidden="true"></i>Добавить группу</a></li>
                    <li><a href="@Url.Action("AppendGroupsAccount","Group",new { UserId = @Model.UserId })"><i class="fa fa-users" aria-hidden="true"></i>Добавить группу пользователю</a></li>
                    <li><a href="@Url.Action("AppendRole","Role",new { UserId = @Model.UserId })"><i class="fa fa-id-card-o" aria-hidden="true"></i>Добавить роль</a></li>
                    <li><a href="@Url.Action("AppendRoleAccount","Role",new { UserId = @Model.UserId })"><i class="fa fa-id-card-o" aria-hidden="true"></i>Добавить пользователю роль</a></li>
                    <li><a href="@Url.Action("Index","Document",new { UserId = @Model.UserId })"><i class="fa fa-file-o" aria-hidden="true"></i>Мои документы</a></li>
                    <li><a href="@Url.Action("DocumentDeleted","Document",new { UserId = @Model.UserId })"><i class="fa fa-shopping-basket" aria-hidden="true"></i>Корзина документов</a></li>
                    <li>
                        <a href="@Url.Action("MessageForUsers","Message",new { UserId = @Model.UserId })">
                            <i class="fa fa-comment-o" aria-hidden="true"></i>Почта
                            <div id="mail">@Model.HelpersDisplayCountMessage</div>
                        </a>
                    </li>
                    <li><a href="@Url.Action("Index","Message",new { UserId = @Model.UserId })"><i class="fa fa-comment-o" aria-hidden="true"></i>Отправить сообщение</a></li>
                    <li>
                        <a href="@Url.Action("MessageDeleted","Message",new { UserId = @Model.UserId })">
                            <i class="fa fa-shopping-basket" aria-hidden="true"></i>Удаленные сообщения
                            <div id="mail">@Model.HelpersDeletedCountMessage</div>
                        </a>
                    </li>
                   </ul>
            </nav>
        </div>
        <div class="base-home-content">
            <div class="base-home-content-information">
                <div class="base-home-content-information-pos">
                    <label for=""><i class="fa fa-comment-o" aria-hidden="true"></i>Почта</label>
                </div>
            </div>
            <div class="container-search">
                @using (Html.BeginForm("Index", "Message", FormMethod.Get))
                {
                    @Html.Hidden("UserId",Model.UserId)
                    <div class="container-search-inputs">
                        <div class="block-input">
                            <div class="block-label-loc">
                                @Html.Label("MiddleName", "Фамлия")
                            </div>
                            <div class="">
                                @Html.TextBox("MiddleName", null, new { type = "text" })
                            </div>
                        </div>
                        <div class="block-input">
                            <div class="block-label-loc">
                                @Html.Label("Name", "Имя")
                            </div>
                            <div class="">
                                @Html.TextBox("Name", null, new { type = "text" })
                            </div>
                        </div>
                        <div class="block-input">
                            <div class="block-label-loc">
                                @Html.Label("LastName", "Отчество")
                            </div>
                            <div class="">
                                @Html.TextBox("LastName", null, new { type = "text" })
                            </div>
                        </div>
                        <div class="block-input">
                            <div class="block-label-loc">
                                @Html.Label("Email", "Почта")
                            </div>
                            <div class="">
                                @Html.TextBox("Email", null, new { type = "text" })
                            </div>
                        </div>
                        <div class="block-input">
                            <div class="block-label-loc">
                                @Html.Label("UserName", "Имя пользователя")
                            </div>
                            <div class="">
                                @Html.TextBox("UserName", null, new { type = "text" })
                            </div>
                        </div>
                    </div>
                    <div class="block-input-sumbit">
                        <input type="submit" name="" value="Найти">
                    </div>
                }
            </div>
            <div class="container-table-user-search">
                <table>
                    @{
                        <tr class="container-table-user-search-main">
                            <th>Фамлия</th>
                            <th>Имя</th>
                            <th>Отчество</th>
                            <th>Почта</th>
                            <th>Имя пользователя</th>
                            <th>Отправить сообщение</th>
                        </tr>
                        @foreach (var message in Model.Participants)
                        {
                            <tr class="container-table-user-search-list">
                                <td>@message.MiddleName</td>
                                <td>@message.Name</td>
                                <td>@message.MiddleName</td>
                                <td>@message.User.UserName</td>
                                <td>@message.User.Email</td>
                                <td><a id="openmessage" href="@Url.ActionLink("MessageSend","Message",
                                                             new { UserSenderId = Model.UserId, UserRecipientId = message.UserId })">Отправить</a></td>
                            </tr>
                        }
                    }
                </table>
                <ul class="pagination">
                    @{
                        <li>
                            <a asp-route-page="@(Model.ListUserMessagePagination.CurrentPage > 0 ?  Model.ListUserMessagePagination.CurrentPage - 1 : 0)"
                               asp-route-Sorting="@Model.ListUserMessageSorting.Default"
                               asp-route-Middlename="@Model.MiddleName"
                               asp-route-Name="@Model.Name"
                               asp-route-LastName="@Model.LastName"
                               asp-route-Email="@Model.Email"
                               asp-route-UserId="@Model.UserId">«</a>
                        </li>
                        for (int i = 1; i < Model.ListUserMessagePagination.TotalPage + 1; i++)
                        {
                            if (Model.ListUserMessagePagination.After)
                            {
                                <li>
                                    <a asp-route-page="@(@i)"
                                       asp-route-Sorting="@Model.ListUserMessageSorting.Default"
                                       asp-route-Middlename="@Model.MiddleName"
                                       asp-route-Name="@Model.Name"
                                       asp-route-LastName="@Model.LastName"
                                       asp-route-Email="@Model.Email"
                                       asp-route-UserId="@Model.UserId">@i</a>
                                </li>
                            }
                            else
                            if (Model.ListUserMessagePagination.Bofore)
                            {
                                <li>
                                    <a asp-route-page="@(@i)"
                                       asp-route-Sorting="@Model.ListUserMessageSorting.Default"
                                       asp-route-Middlename="@Model.MiddleName"
                                       asp-route-Name="@Model.Name"
                                       asp-route-LastName="@Model.LastName"
                                       asp-route-Email="@Model.Email"
                                       asp-route-UserId="@Model.UserId">@i</a>
                                </li>
                            }
                        }
                        <li>
                            <a asp-route-page="@(Model.ListUserMessagePagination.CurrentPage < Model.ListUserMessagePagination.TotalPage ?  Model.ListUserMessagePagination.CurrentPage + 1 : Model.ListUserMessagePagination.TotalPage)"
                               asp-route-Sorting="@Model.ListUserMessageSorting.Default"
                               asp-route-Middlename="@Model.MiddleName"
                               asp-route-Name="@Model.Name"
                               asp-route-LastName="@Model.LastName"
                               asp-route-Email="@Model.Email"
                               asp-route-UserId="@Model.UserId">»</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
</body>
</html>