Models/ModelControllers/Front.cs
using OpenSourceEntitys.Models.ModelControllers.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OpenSourceEntitys.Models.ModelControllers
{
    public class Front
    {
        [Required(ErrorMessage = "Не заполнено")]
        [StringLength(20, MinimumLength = 5, ErrorMessage = "Количество символов должено содержать от 5 до 20")]
        [AttEmail(new string[] {"@bk.ru","@bk.com", "@mail.ru", "@mail.com" }, ErrorMessage = "Не корректно указан адрес электронной почты. Выберите следующие домены @bk.ru,@bk.com,@mail.ru,@mail.com ")]
        public string Email { get; set; }

        public int ParticipantCount { get; set; }

        public int GroupCount { get; set; }
    }
}

Controllers/AuthorizationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.Entitys;
using OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.SystemStorage.StorageEntityContext.RepositoryLogger.IUnitLogOfWork;
using OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.SystemStorage.StorageEntityContext.UnitOfWork;
using OpenSourceEntitys.Models.ModelControllers;
using OpenSourceEntitys.Models.ModelControllers.HomeService;
using OpenSourceEntitys.Models.ServiceUser;
using static OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.SystemStorage.StorageEntityContext.RepositoryLogger.LoggingTypes.LoggingEnum;

namespace OpenSourceEntitys.Controllers
{
    public class AuthorizationController : Controller
    {
        private readonly ILogger<AuthorizationController> _logger;

        private UserManager<User> UserManager { get; set; }

        private ServiceUser ServiceUser { get; set; }

        private SignInManager<User> SignInManager { get; set; }

        private IUnitLogOfWork UnitLogOfWork { get; set; }

        public AuthorizationController(
            ILogger<AuthorizationController> logger,
            UserManager<User> UserManager,
            SignInManager<User> SignInManager,
            ServiceUser ServiceUser,
            IUnitLogOfWork UnitLogOfWork
            )
        {
            _logger = logger;
            this.UserManager = UserManager;
            this.SignInManager = SignInManager;
            this.ServiceUser = ServiceUser;
            this.UnitLogOfWork = UnitLogOfWork;
        }

        [HttpGet]
        public IActionResult Index(string Url = null)
        {
            return View(new Authorization { AuthorizationLink = Url });
        }

        [HttpPost]
        public async Task<IActionResult> Index(Authorization author)
        {
            if(ModelState.IsValid)
            {
                var authorconfirm = await SignInManager.PasswordSignInAsync(author.Email, author.Password,true,false);

                if (authorconfirm.Succeeded)
                {
                    if(!string.IsNullOrEmpty(author.AuthorizationLink) && Url.IsLocalUrl(author.AuthorizationLink))
                    {
                        return Redirect(author.AuthorizationLink);
                    }
                    else
                    {
                        await ServiceUser.Entrance(UserManager.FindByEmailAsync(author.Email).Result);

                        await UnitLogOfWork.RepositoryLogging.InsertLog(UserManager.FindByEmailAsync(author.Email).Result.Id, InformationLoggingEnum.Userloginattempt);

                        return RedirectToAction("Index","Home");
                    }
                }
            }

            return View(author);
        }
    }
}

Controllers/FrontController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using OpenSourceEntitys.Models;
using OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.Entitys;
using OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.SystemStorage.StorageEntityContext.UnitOfWork;
using OpenSourceEntitys.Models.ModelControllers;

namespace OpenSourceEntitys.Controllers
{
    public class FrontController : Controller
    {
        private readonly ILogger<FrontController> _logger;

        private IUnitOfWork UnitOfWork { get; set; }

        private UserManager<User> UserManager { get; set; }

        public FrontController(
            ILogger<FrontController> logger,
            IUnitOfWork UnitOfWork,
            UserManager<User> UserManager
            )
        {
            _logger = logger;
            this.UnitOfWork = UnitOfWork;
            this.UserManager = UserManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(new Front
            {
                GroupCount = UnitOfWork.RepositoryGroups.GetEntitys().Result.Count(),
                ParticipantCount = UnitOfWork.RepositoryParticipant.GetEntitys().Result.Count()
            }) ;
        }

        [HttpPost]
        public async Task<IActionResult> Index(Front front)
        {
            if (ModelState.IsValid)
            {
                var searchreguesr = await UserManager.FindByEmailAsync(front.Email);

                if(searchreguesr == null)
                {
                    return RedirectToActionPermanent("Index","Registration", new { FrontEmail = front.Email });
                }
            }

            return View(new Front
            {
                GroupCount = UnitOfWork.RepositoryGroups.GetEntitys().Result.Count(),
                ParticipantCount = UnitOfWork.RepositoryParticipant.GetEntitys().Result.Count()
            });
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Front/Index.cshtml
@model OpenSourceEntitys.Models.ModelControllers.Front

@{
    ViewData["Title"] = "Index";
}


<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="~/css/font-awesome-4.7.0\css\font-awesome.min.css">
    <link rel="stylesheet" href="~/css/main.css">
    <link rel="stylesheet" href="~/css/Front.css">
    <link rel="stylesheet" href="~/css/FrontMenu.css">
    <title></title>
</head>
<body>
    <div class="list-navigation">
        <nav>
            <ul>
                <li><i class="search-f fa fa-search" aria-hidden="true"><input type="text" name="" value=""></i></li>
            </ul>
            <ul class="pos">
                <li><a href="@Url.Action("Index","Front")"><i class="fa fa-globe" aria-hidden="true"></i>Главная</a></li>
                <li><a href="@Url.Action("ListUsersGroups","Group")"><i class="fa fa-users" aria-hidden="true"></i>Группы</a></li>
                <li><a href="@Url.Action("Index","Registration")"><i class="fa fa-user-plus" aria-hidden="true"></i>Регистрация</a></li>
                <li><a href="@Url.Action("Index","Authorization")"><i class="fa fa-user" aria-hidden="true"></i>Вход</a></li>
                <li><a href="@Url.Action("Index","Front")"><i class="fa fa-map-o" aria-hidden="true"></i>О Сайте</a></li>
            </ul>
        </nav>
    </div>
    <div class="base-container">
        <div class="location">
            <div class="container-information">
                <div class="information">
                    <label for="">Добро пожаловать в OpenSource</label>
                </div>
                <div class="information-p">
                    @{ 
                        <div class="information-p1">
                            @if(Model.ParticipantCount == 0)
                            {
                                <label for="">Количество пользователей: 0</label>
                            }
                            else
                            {
                        <label for="">Количество пользователей: @Model.ParticipantCount</label>
                            }
                        </div>
                        <div class="information-p2">
                            @if (Model.GroupCount == 0)
                            {
                                <label for="">Группы: 0</label>
                            }
                            else
                            {
                                <label for="">Группы: @Model.GroupCount</label>
                            }
                        </div>
                     }
                </div>
            </div>
            <div class="container-reg">
                <div class="container-reg-email">
                    @using (Html.BeginForm("Index", "Front", FormMethod.Post))
                    {
                        <div class="Validation" asp-validation-summary="ModelOnly"></div>
                        <div class="container-lable-1">
                            @Html.Label("Email", "Укажите адрес электронной почты")
                        </div>
                        <div class="container-input-nav">
                            <span asp-validation-for="Email"></span>
                        </div>
                        <div class="container-input-email">
                            @Html.TextBox("Email", null, new { type = "text" })
                        </div>
                        <div class="container-submit-email">
                            <input type="submit" name="" value="Зарегистрировать">
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</body>
</html>