Models/EntityConfiguration/EntitySystem/Entitys/Document.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.Entitys
{
    public class Document
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }

        public string Name { get; set; }

        public byte[] Text { get; set; }

        public string DateCreate { get; set; }

        public bool IsDeleted { get; set; }

        public string DateDeleted { get; set; }

        [ForeignKey("RoleId")]
        public string UserId { get; set; }

        public User User { get; set; }

        [ForeignKey("DocumentTypeId")]
        public int DocumentTypeId { get; set; }

        public DocumentType DocumentType { get; set; }
    }
}

Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.ApplicationContext;
using OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.Entitys;
using OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.SystemStorage.StorageEntityContext.RepositoryLogger.IUnitLogOfWork;
using OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.SystemStorage.StorageEntityContext.UnitOfWork;
using OpenSourceEntitys.Models.ModelControllers;
using OpenSourceEntitys.Models.ModelControllers.ListDocument.ListUserDeletedDocument;
using OpenSourceEntitys.Models.ModelControllers.ListDocument.ListUserForDocument;
using OpenSourceEntitys.Models.ServiceDocument;
using static OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.SystemStorage.StorageEntityContext.RepositoryLogger.LoggingTypes.LoggingEnum;
using static OpenSourceEntitys.Models.ModelControllers.ListDocument.ListUserDeletedDocument.ListUserDeletedDocumentSorting;
using static OpenSourceEntitys.Models.ModelControllers.ListDocument.ListUserForDocument.ListUserForDocumentSorting;

namespace OpenSourceEntitys.Controllers
{
    [Authorize]
    public class DocumentController : Controller
    {
        private readonly ILogger<DocumentController> _logger;

        private UserManager<User> UserManager { get; set; }

        private SignInManager<User> SignInManager { get; set; }

        private IDocumentService DocumentService { get; set; }

        private EntitySourceContext EntitySourceContext { get; set; }

        private IUnitOfWork UnitOfWork { get; set; }

        private IUnitLogOfWork UnitLogOfWork { get; set; }

        public DocumentController(
            ILogger<DocumentController> logger,
            UserManager<User> UserManager,
            SignInManager<User> SignInManager,
            EntitySourceContext EntitySourceContext,
            IDocumentService DocumentService,
            IUnitOfWork UnitOfWork,
            IUnitLogOfWork UnitLogOfWork
            )
        {
            _logger = logger;
            this.UserManager = UserManager;
            this.EntitySourceContext = EntitySourceContext;
            this.UnitOfWork = UnitOfWork;
            this.SignInManager = SignInManager;
            this.DocumentService = DocumentService;
            this.UnitLogOfWork = UnitLogOfWork;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string UserId, string Name, string DateCreate, int? DocumentId, int page = 1, DocumentForSorting Sorting = DocumentForSorting.DocumentAsc)
        {
            if (DocumentId != null)
                await DocumentService.DeleteDocument(UserId, DocumentId);

            var selectlistdoctype = await UnitOfWork.RepositoryDocumentType.GetEntitys();

            var listdocument = await DocumentService.GetListUserDocuments(UserId);

            ListUserForDocumentFiltering ListUsersFiltering = new ListUserForDocumentFiltering(listdocument);

            var filtering = ListUsersFiltering.ListDocumentGetFiltering(Name, DateCreate, UserId);

            ListUserForDocumentSorting ListUserForDocumentSorting = new ListUserForDocumentSorting(Sorting);

            var sorting = ListUserForDocumentSorting.GetListDocumentForSorting(filtering, Sorting);

            ListUserForDocumentPagination ListUserForDocumentPagination = new ListUserForDocumentPagination(page, 7, listdocument.Count());

            await UnitLogOfWork.RepositoryLogging.InsertLog(UserId, InformationLoggingEnum.Gettingpagedatamydocuments);

            return View(new UserDocument
            {
                UserId = UserId,
                Name = Name,
                DateCreate = DateCreate,
                Documents = sorting.Skip((page - 1) * 7).Take(7),
                ListUserForDocumentFiltering = ListUsersFiltering,
                ListUserForDocumentSorting = ListUserForDocumentSorting,
                ListUserForDocumentPagination = ListUserForDocumentPagination,
                DocumentTypes = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(selectlistdoctype, "id","NameType"),
                HelpersDisplayCountMessage = EntitySourceContext.addresSents
                       .Include(t => t.User).Where(t => t.UserId == UserId || t.RecipientId == UserId).ToList().Count(),
                HelpersDeletedCountMessage = EntitySourceContext.MessageSettings
                           .Include(t => t.Message).ThenInclude(t => t.AddresSent).ThenInclude(t => t.User)
                           .Where(t => (t.UserId == UserId && t.MessageDonorIsHidden == true)
                           || (t.UserRecipientId == UserId && t.MessageRecipientIsHidden == true)).ToList().Count()
            });
        }


        [HttpGet]
        public async Task<IActionResult> CreateDocument(string UserId , int page = 1)
        {
            var listdocument = await DocumentService.GetListUserDocuments(UserId);

            ListUserForDocumentPagination ListUserForDocumentPagination = new ListUserForDocumentPagination(page, 7, listdocument.Count());
            await UnitLogOfWork.RepositoryLogging.InsertLog(UserId, InformationLoggingEnum.Addingadocument);

            return View(new CreateDocument
            {
                UserId = UserId,
                Documents = listdocument.Skip((page - 1) * 7).Take(7),
                ListUserForDocumentPagination = ListUserForDocumentPagination,
                HelpersDisplayCountMessage = EntitySourceContext.addresSents
                .Include(t => t.User).Where(t => t.UserId == UserId || t.RecipientId == UserId).ToList().Count(),
                HelpersDeletedCountMessage = EntitySourceContext.MessageSettings
                .Include(t => t.Message).ThenInclude(t => t.AddresSent).ThenInclude(t => t.User)
                .Where(t => (t.UserId == UserId && t.MessageDonorIsHidden == true)
                || (t.UserRecipientId == UserId && t.MessageRecipientIsHidden == true)).ToList().Count()
            }) ;
        }

        [HttpPost]
        public async Task<IActionResult> CreateDocument(CreateDocument CreateDocument)
        {
            bool type = false;

            if (!string.IsNullOrEmpty(CreateDocument?.Avatar?.FileName))
            {
                type = DocumentService.GetTypeIsValid(CreateDocument.Avatar.FileName);
            }

            if (type == false)
            {
                ModelState.AddModelError("Avatar", "Тип не поддерживается");
            }

            if (ModelState.IsValid)
            {
                await DocumentService.CreateDocument(CreateDocument.UserId, CreateDocument.Avatar);
            }

            var listdocument = await DocumentService.GetListUserDocuments(CreateDocument.UserId);

            ListUserForDocumentPagination ListUserForDocumentPagination = new ListUserForDocumentPagination(1, 7, listdocument.Count());

            return View(new CreateDocument
            {
                UserId = CreateDocument.UserId,
                Documents = listdocument.Skip((1 - 1) * 7).Take(7),
                ListUserForDocumentPagination = ListUserForDocumentPagination,
                HelpersDisplayCountMessage = EntitySourceContext.addresSents
                .Include(t => t.User).Where(t => t.UserId == CreateDocument.UserId || t.RecipientId == CreateDocument.UserId).ToList().Count(),
                HelpersDeletedCountMessage = EntitySourceContext.MessageSettings
                .Include(t => t.Message).ThenInclude(t => t.AddresSent).ThenInclude(t => t.User)
                .Where(t => (t.UserId == CreateDocument.UserId && t.MessageDonorIsHidden == true)
                || (t.UserRecipientId == CreateDocument.UserId && t.MessageRecipientIsHidden == true)).ToList().Count()
            });
        }

        [HttpGet]
        public async Task<IActionResult> DocumentDeleted(string UserId, string Name, string DateDeleted, int page = 1, DocumentDeletedSorting DelSorting = DocumentDeletedSorting.DocumentAsc)
        {
            var selectlistdoctype = await UnitOfWork.RepositoryDocumentType.GetEntitys();

            var listdocument = await DocumentService.GetListDelUserDocuments(UserId);

            ListUserDeletedDocumentFiltering ListUsersFiltering = new ListUserDeletedDocumentFiltering(listdocument);

            var filtering = ListUsersFiltering.ListDocumentGetFiltering(Name, DateDeleted, UserId);

            ListUserDeletedDocumentSorting ListUserForDocumentSorting = new ListUserDeletedDocumentSorting(DelSorting);

            var sorting = ListUserForDocumentSorting.GetListDocumentDeletedSorting(filtering, DelSorting);

            ListUserDeletedDocumentPagination ListUserDeletedDocumentPagination = new ListUserDeletedDocumentPagination(page, 7, listdocument.Count());

            await UnitLogOfWork.RepositoryLogging.InsertLog(UserId, InformationLoggingEnum.RetrievingDocumentBasketPageData);

            return View(new DocumentDeleted
            {
                UserId = UserId,
                Name = Name,
                DateDeleted = DateDeleted,
                Documents = sorting.Skip((page - 1) * 7).Take(7),
                ListUserDeletedDocumentFiltering = ListUsersFiltering,
                ListUserDeletedDocumentSorting = ListUserForDocumentSorting,
                ListUserDeletedDocumentPagination = ListUserDeletedDocumentPagination,
                DocumentTypes = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(selectlistdoctype, "id", "NameType"),
                HelpersDisplayCountMessage = EntitySourceContext.addresSents
                .Include(t => t.User).Where(t => t.UserId == UserId || t.RecipientId == UserId).ToList().Count(),
                HelpersDeletedCountMessage = EntitySourceContext.MessageSettings

Controllers/FrontController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using OpenSourceEntitys.Models;
using OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.Entitys;
using OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.SystemStorage.StorageEntityContext.UnitOfWork;
using OpenSourceEntitys.Models.ModelControllers;

namespace OpenSourceEntitys.Controllers
{
    public class FrontController : Controller
    {
        private readonly ILogger<FrontController> _logger;

        private IUnitOfWork UnitOfWork { get; set; }

        private UserManager<User> UserManager { get; set; }

        public FrontController(
            ILogger<FrontController> logger,
            IUnitOfWork UnitOfWork,
            UserManager<User> UserManager
            )
        {
            _logger = logger;
            this.UnitOfWork = UnitOfWork;
            this.UserManager = UserManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(new Front
            {
                GroupCount = UnitOfWork.RepositoryGroups.GetEntitys().Result.Count(),
                ParticipantCount = UnitOfWork.RepositoryParticipant.GetEntitys().Result.Count()
            }) ;
        }

        [HttpPost]
        public async Task<IActionResult> Index(Front front)
        {
            if (ModelState.IsValid)
            {
                var searchreguesr = await UserManager.FindByEmailAsync(front.Email);

                if(searchreguesr == null)
                {
                    return RedirectToActionPermanent("Index","Registration", new { FrontEmail = front.Email });
                }
            }

            return View(new Front
            {
                GroupCount = UnitOfWork.RepositoryGroups.GetEntitys().Result.Count(),
                ParticipantCount = UnitOfWork.RepositoryParticipant.GetEntitys().Result.Count()
            });
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ListUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.ApplicationContext;
using OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.Entitys;
using OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.SystemStorage.StorageEntityContext.RepositoryLogger.IUnitLogOfWork;
using OpenSourceEntitys.Models.ModelControllers;
using OpenSourceEntitys.Models.ModelControllers.ListUsers.ListUserService;
using OpenSourceEntitys.Models.ModelControllers.ListUsersView;
using OpenSourceEntitys.Models.ModelCore;
using static OpenSourceEntitys.Models.EntityConfiguration.EntitySystem.SystemStorage.StorageEntityContext.RepositoryLogger.LoggingTypes.LoggingEnum;
using static OpenSourceEntitys.Models.ModelControllers.ListUsers.ListUserService.ListParticipantSorting;

namespace OpenSourceEntitys.Controllers
{
    [Authorize]
    public class ListUserController : Controller
    {
        private readonly ILogger<ListUserController> _logger;

        private UserManager<User> UserManager { get; set; }

        private IListParticipantService IListUserService { get; set; }

        private EntitySourceContext EntitySourceContext { get; set; }

        private IUnitLogOfWork UnitLogOfWork { get; set; }

        public ListUserController(
            ILogger<ListUserController> logger,
            IListParticipantService IListUserService,
            UserManager<User> UserManager,
            EntitySourceContext EntitySourceContext,
            IUnitLogOfWork UnitLogOfWork
            )
        {
            _logger = logger;
            this.UserManager = UserManager;
            this.EntitySourceContext = EntitySourceContext;
            this.IListUserService = IListUserService;
            this.UnitLogOfWork = UnitLogOfWork;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string UserId, string MiddleName, string Name, string LastName, string Email, string UserName, int page = 1, Sorting Sorting = Sorting.NameAsc)
        {
            var listuser = await IListUserService.GetListUserService();

            ListParticipantFiltering ListUsersFiltering = new ListParticipantFiltering(listuser);

            var filtering = ListUsersFiltering.ListUsersGetFiltering(MiddleName, Name, LastName, Email, UserName);

            ListParticipantSorting ListParticipantSorting = new ListParticipantSorting(Sorting);

            var sorting = ListParticipantSorting.GetListParticipantSorting(filtering, Sorting);

            ListParticipantPagination ListUsersPagination = new ListParticipantPagination(page, 7, listuser.Count());

            await UnitLogOfWork.RepositoryLogging.InsertLog(UserId, InformationLoggingEnum.Gettinguserpagedata);

            return View(new ListUser
            {
                MiddleName = MiddleName,
                Name = Name,
                LastName = LastName,
                UserId = UserId,
                Email = Email,
                UserName = UserName,
                Participants = sorting.Skip((page - 1) * 7).Take(7),
                ListUsersSorting = ListParticipantSorting,
                ListUsersPagination = ListUsersPagination,
                HelpersDisplayCountMessage = EntitySourceContext.addresSents
                .Include(t => t.User).Where(t => t.UserId == UserId || t.RecipientId == UserId).ToList().Count(),
                HelpersDeletedCountMessage = EntitySourceContext.MessageSettings
                .Include(t => t.Message).ThenInclude(t => t.AddresSent).ThenInclude(t => t.User)
                .Where(t => (t.UserId == UserId && t.MessageDonorIsHidden == true)
                || (t.UserRecipientId == UserId && t.MessageRecipientIsHidden == true)).ToList().Count()

            }); 

        }
    }
}

Views/Document/CreateDocument.cshtml
@model OpenSourceEntitys.Models.ModelControllers.CreateDocument

@{
    ViewData["Title"] = "CreateDocument";
}

<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="~/css/font-awesome-4.7.0\css\font-awesome.min.css">
    <link rel="stylesheet" href="~/css/main.css">
    <link rel="stylesheet" href="~/css/HomeFrontMenu.css">
    <link rel="stylesheet" href="~/css/HomeMenu.css">
    <link rel="stylesheet" href="~/css/CreateDocument.css">
    <title></title>
</head>
<body>
    <div class="list-navigation">
        <nav>
            <ul>
                <li><i class="search-f fa fa-search" aria-hidden="true"><input type="text" name="" value=""></i></li>
            </ul>
            <ul class="pos">
                <li><a href="@Url.Action("Index", "Front")"><i class="fa fa-globe" aria-hidden="true"></i>Главная</a></li>
                <li><a href="@Url.Action("ListUsersGroups","Group")"><i class="fa fa-users" aria-hidden="true"></i>Группы</a></li>
                <li><a href="@Url.Action("Index", "Registration")"><i class="fa fa-user-plus" aria-hidden="true"></i>Регистрация</a></li>
                <li><a href="@Url.Action("OutAccount", "Home",new { UserId = @Model.UserId })"><i class="fa fa-user" aria-hidden="true"></i>Выход</a></li>
                <li><a href="@Url.Action("Index", "Front")"><i class="fa fa-map-o" aria-hidden="true"></i>О Сайте</a></li>
            </ul>
        </nav>
    </div>
    <div class="base-container-home">
        <div class="base-home-menu">
            <nav class="">
                <ul>
                    <li><a href="@Url.Action("Index","Home")"><i class="fa fa-user-o" aria-hidden="true"></i>Профиль</a></li>
                    <li><a href="@Url.Action("Index","ListUser",new { UserId = @Model.UserId })"><i class="fa fa-users" aria-hidden="true"></i>Список пользователей</a></li>
                    <li><a href="@Url.Action("UpdateProfile","Home",new { UserId = @Model.UserId })"><i class="fa fa-list-alt" aria-hidden="true"></i>Изменить данные профиля</a></li>
                    <li><a href="@Url.Action("UpdateAccount","Home",new { UserId = @Model.UserId })"><i class="fa fa-list-alt" aria-hidden="true"></i>Изменить данные пользователя</a></li>
                    <li><a href="@Url.Action("UpdatePassword","Home",new { UserId = @Model.UserId })"><i class="fa fa-list-alt" aria-hidden="true"></i>Изменить пароль</a></li>
                    <li><a href="@Url.Action("ListUsersGroups","Group",new { UserId = @Model.UserId })"><i class="fa fa-users" aria-hidden="true"></i>Список групп</a></li>
                    <li><a href="@Url.Action("AppendGroups","Group",new { UserId = @Model.UserId })"><i class="fa fa-users" aria-hidden="true"></i>Добавить группу</a></li>
                    <li><a href="@Url.Action("AppendGroupsAccount","Group",new { UserId = @Model.UserId })"><i class="fa fa-users" aria-hidden="true"></i>Добавить группу пользователю</a></li>
                    <li><a href="@Url.Action("AppendRole","Role",new { UserId = @Model.UserId })"><i class="fa fa-id-card-o" aria-hidden="true"></i>Добавить роль</a></li>
                    <li><a href="@Url.Action("AppendRoleAccount","Role",new { UserId = @Model.UserId })"><i class="fa fa-id-card-o" aria-hidden="true"></i>Добавить пользователю роль</a></li>
                    <li><a href="@Url.Action("Index","Document",new { UserId = @Model.UserId })"><i class="fa fa-file-o" aria-hidden="true"></i>Мои документы</a></li>
                    <li><a href="@Url.Action("DocumentDeleted","Document",new { UserId = @Model.UserId })"><i class="fa fa-shopping-basket" aria-hidden="true"></i>Корзина документов</a></li>
                    <li>
                        <a href="@Url.Action("MessageForUsers","Message",new { UserId = @Model.UserId })">
                            <i class="fa fa-comment-o" aria-hidden="true"></i>Почта
                            <div id="mail">@Model.HelpersDisplayCountMessage</div>
                        </a>
                    </li>
                    <li><a href="@Url.Action("Index","Message",new { UserId = @Model.UserId })"><i class="fa fa-comment-o" aria-hidden="true"></i>Отправить сообщение</a></li>
                    <li>
                        <a href="@Url.Action("MessageDeleted","Message",new { UserId = @Model.UserId })">
                            <i class="fa fa-shopping-basket" aria-hidden="true"></i>Удаленные сообщения
                            <div id="mail">@Model.HelpersDeletedCountMessage</div>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="base-home-content">
            <div class="base-home-content-information">
                <div class="base-home-content-information-pos">
                    <label for=""><i class="fa fa-file-o" aria-hidden="true"></i>Создать документ</label>
                </div>
            </div>
            <div class="base-block-appendgroups">
                @using (Html.BeginForm("CreateDocument", "Document", FormMethod.Post,new { @enctype = "multipart/form-data"}))
                {
                    @Html.Hidden("UserId",Model.UserId)
                    <div class="Validation" asp-validation-summary="ModelOnly"></div>
                    <div class="base-block-appendgroups-con-pos">
                        <div class="base-block-appendgroups-position container-doc-location">
                            <div class="base-block-appendgroups-positflex">
                                <div class="base-block-position-label">
                                    @Html.Label(null, "Выбрать файл")
                                </div>
                                <div class="base-block-position-nav">
                                    <span asp-validation-for="Avatar"></span>
                                </div>
                            </div>
                        </div>
                        <div class="block-submit">
                            <div class="example-2">
                                <div class="form-group">
                                    <input type="file" name="Avatar" id="file" class="input-file">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="bloc-doc-create">
                        <input type="submit" name="" value="Добавить">
                    </div>
                }
                <div class="container-table-file-search">
                    @{
                        <table>
                            <tr class="container-table-file-search-main">
                                <th>Файл</th>
                                <th>Наименование документа</th>
                                <th>Открыть документ</th>
                                <th>Дата добавления документа</th>
                                <th>Тип файла</th>
                            </tr>
                            @foreach (var doc in Model.Documents)
                            {
                                <tr class="container-table-file-search-list">
                                    <td id="td-w-icon"><i id="td-icon" class="fa fa-file-o" aria-hidden="true"></i></td>
                                    <td>@doc.Name</td>
                                    <td><a id="docopen" href="@Url.Action("Download","Document",new { DocumentId = doc.id })">Открыть</a></td>
                                    <td><div id="doctime">@doc.DateCreate</div></td>
                                    <td><div id="doctype">@doc.DocumentType.NameType</div></td>
                                </tr>
                            }
                        </table>
                    }
                    <ul class="pagination">
                        @{
                            <li>
                                <a asp-route-page="@(Model.ListUserForDocumentPagination.CurrentPage > 0 ?  Model.ListUserForDocumentPagination.CurrentPage - 1 : 0)"
                                   asp-route-UserId="@Model.UserId">«</a>
                            </li>
                            for (int i = 1; i < Model.ListUserForDocumentPagination.TotalPage + 1; i++)
                            {
                                if (Model.ListUserForDocumentPagination.After)
                                {
                                    <li>
                                        <a asp-route-page="@(@i)"
                                           asp-route-UserId="@Model.UserId">@i</a>
                                    </li>
                                }
                                else
                                if (Model.ListUserForDocumentPagination.Bofore)
                                {
                                    <li>
                                        <a asp-route-page="@(@i)"
                                           asp-route-UserId="@Model.UserId">@i</a>
                                    </li>
                                }
                            }
                            <li>
                                <a asp-route-page="@(Model.ListUserForDocumentPagination.CurrentPage < Model.ListUserForDocumentPagination.TotalPage ?  Model.ListUserForDocumentPagination.CurrentPage + 1 : Model.ListUserForDocumentPagination.TotalPage)"
                                   asp-route-UserId="@Model.UserId">»</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
</body>
</html>